// Code generated by MockGen. DO NOT EDIT.
// Source: io-factory.go

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIFactory is a mock of IFactory interface.
type MockIFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIFactoryMockRecorder
}

// MockIFactoryMockRecorder is the mock recorder for MockIFactory.
type MockIFactoryMockRecorder struct {
	mock *MockIFactory
}

// NewMockIFactory creates a new mock instance.
func NewMockIFactory(ctrl *gomock.Controller) *MockIFactory {
	mock := &MockIFactory{ctrl: ctrl}
	mock.recorder = &MockIFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFactory) EXPECT() *MockIFactoryMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockIFactory) Build(endpoint, name string) IAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", endpoint, name)
	ret0, _ := ret[0].(IAPI)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockIFactoryMockRecorder) Build(endpoint, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockIFactory)(nil).Build), endpoint, name)
}

// Register mocks base method.
func (m *MockIFactory) Register(endpoint, name string, api IAPI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", endpoint, name, api)
}

// Register indicates an expected call of Register.
func (mr *MockIFactoryMockRecorder) Register(endpoint, name, api interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIFactory)(nil).Register), endpoint, name, api)
}
