// Code generated by MockGen. DO NOT EDIT.
// Source: .\i-identity.go

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIIdentity is a mock of IIdentity interface.
type MockIIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockIIdentityMockRecorder
}

// MockIIdentityMockRecorder is the mock recorder for MockIIdentity.
type MockIIdentityMockRecorder struct {
	mock *MockIIdentity
}

// NewMockIIdentity creates a new mock instance.
func NewMockIIdentity(ctrl *gomock.Controller) *MockIIdentity {
	mock := &MockIIdentity{ctrl: ctrl}
	mock.recorder = &MockIIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIdentity) EXPECT() *MockIIdentityMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockIIdentity) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockIIdentityMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockIIdentity)(nil).GetID))
}
